---
- name: Setup Docker CE repo
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
  become: true
- name: Install Docker CE & Openshift Origin
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - origin
      - iproute
    state: present
  become: true
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
  become: true
- name: Make sure docker is running
  systemd:
    name: docker
    state: started
  become: true
- name: Create docker deamon config
  file:
    path: /etc/docker/daemon.json
    state: touch
    mode: 0644
  become: true
- name: Add OpenShift insecure registry into docker deamon config
  copy:
    content: |
      {"insecure-registries" : [ "172.30.0.0/16" ]}
    dest: /etc/docker/daemon.json
    mode: 0644
  become: true
- name: Restart docker because config has changed
  systemd:
    state: restarted
    daemon_reload: true
    name: docker
  become: true
- command: docker network inspect bridge
  register: docker_network_bridge
  changed_when: false
- debug:
    var: docker_network_bridge
- command: ip a
  register: ip_a
  changed_when: false
- debug:
    var: ip_a
- name: Start Openshift cluster
  command: oc cluster up --base-dir=/tmp --enable="-centos-imagestreams,-sample-templates,persistent-volumes,registry,router,-web-console"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
    DOCKER_CONFIG: "/etc/docker/daemon.json"
  become: true
  changed_when: true
